// Renders build/logo.svg into the raster assets electron-builder + the app need:
//   build/icon.ico   → installer, exe, dev window icon (multi-size)
//   build/icon.png   → 256px master (Linux / fallback)
//   src/main/trayIcon.js → 32px + 16px tray icons inlined as base64 data URLs
//                          (build/ is not packaged, so the tray icon must live in code)
import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'
import sharp from 'sharp'
import pngToIco from 'png-to-ico'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const svg = readFileSync(join(root, 'build', 'logo.svg'))

const png = (size) => sharp(svg, { density: 384 }).resize(size, size).png().toBuffer()

async function main() {
  mkdirSync(join(root, 'build'), { recursive: true })

  const icoSizes = [16, 24, 32, 48, 64, 128, 256]
  const icoBuffers = await Promise.all(icoSizes.map(png))
  writeFileSync(join(root, 'build', 'icon.ico'), await pngToIco(icoBuffers))

  const master = await png(256)
  writeFileSync(join(root, 'build', 'icon.png'), master)

  const tray32 = (await png(32)).toString('base64')
  const tray16 = (await png(16)).toString('base64')
  writeFileSync(
    join(root, 'src', 'main', 'trayIcon.js'),
    `// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.\n` +
      `export const trayIcon32 = 'data:image/png;base64,${tray32}'\n` +
      `export const trayIcon16 = 'data:image/png;base64,${tray16}'\n`
  )

  console.log('icons generated: build/icon.ico, build/icon.png, src/main/trayIcon.js')
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
